# We use Node because we need the 'npm run dev' robot
FROM node:16-bookworm
WORKDIR /app
# We only copy package files to install deps.
# Source code is mounted via Volumes in docker-compose.
COPY package.json yarn.lock ./
RUN npm install
EXPOSE 8080
CMD ["npm", "run", "dev"]