# Generated by Django 3.2.25 on 2025-12-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20251202_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.TextField(default='Unranked'),
        ),
    ]
